### ISSUE TITLE
Compatability EEPROM/SPIFFS/OTA

### ISSUE THREAD

**Issue by bertmelis** [krzychb/EspSaveCrash#2]
I'm using the Homie-framework (https://github.com/marvinroger/homie-esp8266) which stores a config file n SPIFFS. When I'm doing a OTA update using this framework, the config file gets lost somehow.

I did not see this behaviour prior to using the EspSaveCrash library. I suspect an incompatability between the EEPROM, SPIFFS and sketch (OTA) layout.

I didn't alter the basic settings for memory layout.

**Comment by krzychb** [comment]
Hi @bertmelis,

>  I suspect an incompatability between the EEPROM, SPIFFS and sketch (OTA) layout.

Basing on [EEPROM documentation](https://arduino-esp8266.readthedocs.io/en/latest/libraries.html#eeprom), "EEPROM library uses one sector of flash located just after the SPIFFS."
This provides reasonable evidence, that layout of EEPROM and SPIFFS should be compatible.

> When I'm doing a OTA update using this framework, the config file gets lost somehow." 

I would remove EspSaveCrash library and check once more if  config file survives or get lost.

**Comment by bertmelis** [comment]
After removing the EspSaveCrash lib OTA works again. So I'm probably doing something wrong here.
I'm using a Wemos D1 mini, 4M/1M, sketch size is about 380kB. The config file is about 50kB.

Homie's OTA update uses UpdaterClass from the ESP8266-Arduino-core.

I could test a lot, but this is unexplored terrain for me.

**Comment by proddy** [comment]
I have the same question. I want to use this fantastic library with my code that uses both SPIFFS and OTA on a Wemos D1 4MB and I think they might be interfering. Do you know a safe start/offset to use?
