### ISSUE TITLE
Printing crash to string

### ISSUE THREAD

**Issue by Masterpc96** [krzychb/EspSaveCrash#7]
It is possible to print crash to String? I am using AsyncWebserver and I want to send crash via web using it

**Comment by MaxMaeder** [comment]
This would definitely be useful!

**Comment by brainelectronics** [comment]
checkout my pull request https://github.com/krzychb/EspSaveCrash/pull/9. 
It enables you to send crash log data to a custom char buffer. This can than be shown by a webserver, I've therefore also updated the RemoteCrashCheck example.

**Comment by krzychb** [comment]
Resolved with cf29dd4005e2972a42c213a5a5c30223b1bef446. Thank you  @brainelectronics :+1:
